import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/Theme/theme'
import Section from '@/components/Section';
import Footer from '@/components/Footer';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{backgroundColor: 'white'}}>
        <ThemeProvider theme={theme}>
          <Header/>
          <Section />
          <Footer />
          <>
          <br/>
          <br/>
          <br/>
          <br/>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt ea necessitatibus quam consectetur magni quidem quo, eaque aut perspiciatis deleniti omnis cupiditate odio laborum nisi illo dicta itaque amet nam.
          </>
        </ThemeProvider>
      </main>
    </>
  )
}
